### ISSUE TITLE
Remove name and description from composer json in php-component template

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/component-generator#14]
Ref. https://github.com/keboola/processor-orthogonal/pull/1#discussion_r176035533

Repends on https://github.com/composer/composer/issues/7207

**Comment by tomasfejfar** [comment]
Or not. https://github.com/keboola/connection/pull/1275

**Comment by Halama** [comment]
Nenastavíme to teda zatím stejně jako je to teď v [connection](https://github.com/keboola/connection/blob/43b83e4d4f12f33c3fd285b7749f648292c5bb4f/composer.json#L62) tzn. bez `--strict`?

**Comment by tomasfejfar** [comment]
Jo, asi bysme mohli. Zkouknul bys tu composer issue, jestli to nevysvětluju nějak moc zmatečně. Mám pocit, že mi pořád nerozumí.

**Comment by odinuv** [comment]
ja bych byl pro, tohle se tyka veci, ktery v 99% nejdou na packagist

**Comment by Halama** [comment]
Tu composer issue sleduju a přijde mi to srozumitelné, zvlášt ten poslední komentář. Bohužel bez reakce, kdyžtak bych tam mohl zkusit něco napsat pro oživení pokud se tam nebude pár dní nic dít.
