### ISSUE TITLE
Bitbucket Pipelines ci generator 

### ISSUE THREAD

**Issue by Halama** [keboola/component-generator#25]
- Bitbucket Pipelines requires Bitbucket repo, but generator supports only Github
- Generated project contains also `.travis.yml` file which shouldn't be there
- Generator supports only travis
- Dockerfile is missing

So I think it shouldn't be part of generator.

**Comment by Halama** [comment]
IMHO it should be mentioned only in [docs](https://developers.keboola.com/extend/component/deployment/#bitbucket-integration)

**Comment by tomasfejfar** [comment]
Řešilo by to, kdyby byly "generator tasks" https://github.com/keboola/component-generator/issues/8#issuecomment-374254767

**Comment by odinuv** [comment]
duplicate of https://github.com/keboola/component-generator/issues/8
