### ISSUE TITLE
Missing phpcs

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/component-generator#55]
`php-component` template [no longer requires `squizlabs/php_codesniffer` directly](https://github.com/keboola/component-generator/blob/master/templates/php-component/composer.json), only through `keboola/coding-standard`. That results in missing `phpcs` executable in `vendor/bin`.

**Comment by Actimel** [comment]
You are right, `php-component` does not require `squizlabs/php_codesniffer`, but `keboola/coding-standard` does. That results in creating `.../vendor/bin/phpcs`.

I am not sure what happened to you when you create this issue, but `phpcs` works for me now.

**Comment by tomasfejfar** [comment]
Agreed. 
![image](https://user-images.githubusercontent.com/642928/42271138-deb71cb6-7f82-11e8-95b9-b3e0656c1b02.png)
