### ISSUE TITLE
Remove composer.lock from templates

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/component-generator#61]
New component should have latest version of dependencies. Current situation leads to the need of regular updating on generator templates.

**Comment by ondrejhlavacek** [comment]
PROTI

- Může se stát, že si vygeneruješ appku, co bude mít v sobě chyby. Dal bych tam jen ověřený věci. 

PRO

- Update kvůli nové verzi každé blbosti.
- Semver. Výše popsané by nemělo nastat.
- Pokud nastane, fixne se v generátoru a pofrčí to.

**Comment by tomasfejfar** [comment]
@ondrejhlavacek můžeš mít v composer.json přesnou verzi `keboola/php-component: "2.3.1"` a ani bez lockfile se ti to neupdatne. Ale obecně určitě je možné, že někdy se updatnou nějaké nekompatibilní změny. Na druhou stranu, ty by se projevily i tak, náhodně při `composer update` nad komponentou.
